### ISSUE TITLE
Suggestion: add a swear list to the AI.

### ISSUE THREAD

**Issue by felixgao-0** [vzhou842/profanity-check#32]
Make a list that would auto-trigger a swear alert and make it customizable.

**Comment by jtpotato** [comment]
That... defeats the entire point

**Comment by BradKML** [comment]
@FelixGao-discord please explain the reasoning behind this.
If you want to use a wordlist-based system rather than an AI model based on sentence datasets, you should use other libraries.
- https://github.com/LDNOOBW/List-of-Dirty-Naughty-Obscene-and-Otherwise-Bad-Words
- https://github.com/words/cuss
- https://github.com/chucknorris-io/swear-words
- https://github.com/thisandagain/washyourmouthoutwithsoap

**Comment by felixgao-0** [comment]
@BrandonKMLee I mean add a set of words that are always considered swears. Like the f word. In which the ai would check the list as well.
